AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  EmailGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_email_generator::Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 128
      Timeout: 10
