name: Wrapper workflow for svrless lambda

on:
  push:
    branches:
      - "main"
      - "feature**"
  delete:
    branches:
      - "feature**"
  workflow_dispatch:

jobs:
  call-subdirectory-workflows:
    uses: auto-email-sender/svrless-email-lambda/src/svrless-email-lambda/.github/workflows/pipeline.yaml@main
